export const audio = [
  {
    id: '1',
    type: 'audiobook',
    title: 'The Way of Kings',
    rating: 4.8,
    length: 2730,
    tags: ['Fantasy','Storm blessed'],
    art: '',
    info: {
      book: 1,
      series: 'Stormlight Archives',
      author: 'Brandon Sanderson',
      narrator: 'Kate Reading and Michael Kramer',
    },
  },{
    id: '2',
    type: 'audiobook',
    title: 'Words of Radiance',
    rating: 4.9,
    length: 2895,
    tags: ['Fantasy','Storm blessed'],
    art: '',
    info: {
      book: 2,
      series: 'Stormlight Archives',
      author: 'Brandon Sanderson',
      narrator: 'Kate Reading and Michael Kramer',
    },
  },{
    id: '3',
    type: 'audiobook',
    title: 'Rhythm of War',
    rating: 4.8,
    length: 3450,
    tags: ['Fantasy','Storm blessed'],
    art: '',
    info: {
      book: 4,
      series: 'Stormlight Archives',
      author: 'Brandon Sanderson',
      narrator: 'Kate Reading and Michael Kramer',
    },
  },{
    id: '4',
    type: 'audiobook',
    title: 'Oathbringer',
    rating: 4.8,
    length: 3305,
    tags: ['Fantasy','Storm blessed'],
    art: '',
    info: {
      book: 3,
      series: 'Stormlight Archives',
      author: 'Brandon Sanderson',
      narrator: 'Kate Reading and Michael Kramer',
    },
  },{
    id: '5',
    type: 'music',
    title: 'lara',
    rating: 5,
    length: 2.33,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 1,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  },{
    id: '6',
    type: 'music',
    title: 'Dopamine',
    rating: 5,
    length: 3.34,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 2,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  },{
    id: '7',
    type: 'music',
    title: 'Big Sky, MT',
    rating: 5,
    length: 4.59,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 3,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  },{
    id: '8',
    type: 'music',
    title: 'Shoulders',
    rating: 5,
    length: 5.03,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 4,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  },{
    id: '9',
    type: 'music',
    title: 'Little Bird',
    rating: 5,
    length: 3.31,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 5,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  },{
    id: '10',
    type: 'music',
    title: 'Sparrow',
    rating: 5,
    length: 3.39,
    tags: ['folk', '2023'],
    art: '',
    info: {
      artist: 'The Arcadian Wild',
      album: 'Welcome',
      song: 5,
      composer: 'Bailey Warren, Isaac Horn & Lincoln Mick',
      bpm: 0,
    },
  }
];

export const playlist = [
  {
    id: '1',
    title: 'long run',
    rating: 5,
    audio: ['1','2','4','3']
  },
  {
    id: '2',
    title: 'short run',
    rating: 4.3,
    audio: ['5','6','7','8','9','10']
  }
]